from scrapy.spiders import Spider
from scrapy.selector import Selector
from dirbot.items import Website

import re
import os, os.path

class DmozSpider(Spider):
    name = "phev"
    allowed_domains = ["chargecar.org"]
    
    """
    def func_DirWalkThrough(self,dir_name):
        list_webaddr = []
        for root, _, files in os.walk(dir_name):
            for f in files:
                name_txt = f.split('.')
                #print name_txt[0]
                fullpath = "http://www.chargecar.org/data/" + name_txt[0]
                list_webaddr.append(fullpath)
        return list_webaddr

    #start_urls = ["http://www.chargecar.org/data/289"]
    
    def start_requests(self):
        return [self.func_DirWalkThrough("../../../../../../HybridModel/V1_0_ProblemFix/data/Trip_Data")]
    """

    start_urls = ['http://www.chargecar.org/data/613',
 'http://www.chargecar.org/data/609',
 'http://www.chargecar.org/data/646',
 'http://www.chargecar.org/data/439',
 'http://www.chargecar.org/data/438',
 'http://www.chargecar.org/data/10',
 'http://www.chargecar.org/data/574',
 'http://www.chargecar.org/data/602',
 'http://www.chargecar.org/data/599',
 'http://www.chargecar.org/data/147',
 'http://www.chargecar.org/data/155',
 'http://www.chargecar.org/data/666',
 'http://www.chargecar.org/data/287',
 'http://www.chargecar.org/data/548',
 'http://www.chargecar.org/data/549',
 'http://www.chargecar.org/data/743',
 'http://www.chargecar.org/data/661',
 'http://www.chargecar.org/data/531',
 'http://www.chargecar.org/data/530',
 'http://www.chargecar.org/data/289',
 'http://www.chargecar.org/data/315',
 'http://www.chargecar.org/data/286',
 'http://www.chargecar.org/data/403',
 'http://www.chargecar.org/data/405',
 'http://www.chargecar.org/data/401',
 'http://www.chargecar.org/data/402',
 'http://www.chargecar.org/data/404',
 'http://www.chargecar.org/data/273',
 'http://www.chargecar.org/data/281',
 'http://www.chargecar.org/data/279',
 'http://www.chargecar.org/data/277',
 'http://www.chargecar.org/data/274',
 'http://www.chargecar.org/data/275',
 'http://www.chargecar.org/data/276',
 'http://www.chargecar.org/data/280',
 'http://www.chargecar.org/data/282',
 'http://www.chargecar.org/data/11',
 'http://www.chargecar.org/data/12',
 'http://www.chargecar.org/data/284',
 'http://www.chargecar.org/data/285',
 'http://www.chargecar.org/data/283',
 'http://www.chargecar.org/data/111',
 'http://www.chargecar.org/data/110',
 'http://www.chargecar.org/data/491',
 'http://www.chargecar.org/data/493',
 'http://www.chargecar.org/data/492',
 'http://www.chargecar.org/data/532',
 'http://www.chargecar.org/data/411',
 'http://www.chargecar.org/data/408',
 'http://www.chargecar.org/data/407',
 'http://www.chargecar.org/data/533',
 'http://www.chargecar.org/data/409',
 'http://www.chargecar.org/data/410',
 'http://www.chargecar.org/data/541',
 'http://www.chargecar.org/data/257',
 'http://www.chargecar.org/data/263',
 'http://www.chargecar.org/data/694',
 'http://www.chargecar.org/data/709',
 'http://www.chargecar.org/data/729',
 'http://www.chargecar.org/data/706',
 'http://www.chargecar.org/data/731',
 'http://www.chargecar.org/data/698',
 'http://www.chargecar.org/data/704',
 'http://www.chargecar.org/data/727',
 'http://www.chargecar.org/data/702',
 'http://www.chargecar.org/data/720',
 'http://www.chargecar.org/data/723',
 'http://www.chargecar.org/data/718',
 'http://www.chargecar.org/data/696',
 'http://www.chargecar.org/data/737',
 'http://www.chargecar.org/data/714',
 'http://www.chargecar.org/data/700',
 'http://www.chargecar.org/data/742',
 'http://www.chargecar.org/data/740',
 'http://www.chargecar.org/data/725',
 'http://www.chargecar.org/data/735',
 'http://www.chargecar.org/data/733',
 'http://www.chargecar.org/data/721',
 'http://www.chargecar.org/data/736',
 'http://www.chargecar.org/data/719',
 'http://www.chargecar.org/data/699',
 'http://www.chargecar.org/data/708',
 'http://www.chargecar.org/data/734',
 'http://www.chargecar.org/data/693',
 'http://www.chargecar.org/data/730',
 'http://www.chargecar.org/data/695',
 'http://www.chargecar.org/data/732',
 'http://www.chargecar.org/data/710',
 'http://www.chargecar.org/data/703',
 'http://www.chargecar.org/data/728',
 'http://www.chargecar.org/data/724',
 'http://www.chargecar.org/data/717',
 'http://www.chargecar.org/data/739',
 'http://www.chargecar.org/data/741',
 'http://www.chargecar.org/data/738',
 'http://www.chargecar.org/data/707',
 'http://www.chargecar.org/data/726',
 'http://www.chargecar.org/data/697',
 'http://www.chargecar.org/data/701',
 'http://www.chargecar.org/data/705',
 'http://www.chargecar.org/data/610',
 'http://www.chargecar.org/data/612',
 'http://www.chargecar.org/data/577',
 'http://www.chargecar.org/data/575',
 'http://www.chargecar.org/data/582',
 'http://www.chargecar.org/data/584',
 'http://www.chargecar.org/data/579',
 'http://www.chargecar.org/data/339',
 'http://www.chargecar.org/data/292',
 'http://www.chargecar.org/data/385',
 'http://www.chargecar.org/data/317',
 'http://www.chargecar.org/data/604',
 'http://www.chargecar.org/data/386',
 'http://www.chargecar.org/data/601',
 'http://www.chargecar.org/data/608',
 'http://www.chargecar.org/data/556',
 'http://www.chargecar.org/data/573',
 'http://www.chargecar.org/data/310',
 'http://www.chargecar.org/data/311',
 'http://www.chargecar.org/data/578',
 'http://www.chargecar.org/data/603',
 'http://www.chargecar.org/data/581',
 'http://www.chargecar.org/data/600',
 'http://www.chargecar.org/data/605',
 'http://www.chargecar.org/data/576',
 'http://www.chargecar.org/data/312',
 'http://www.chargecar.org/data/585',
 'http://www.chargecar.org/data/580',
 'http://www.chargecar.org/data/583',
 'http://www.chargecar.org/data/607',
 'http://www.chargecar.org/data/324',
 'http://www.chargecar.org/data/606',
 'http://www.chargecar.org/data/318',
 'http://www.chargecar.org/data/387',
 'http://www.chargecar.org/data/648',
 'http://www.chargecar.org/data/260',
 'http://www.chargecar.org/data/298',
 'http://www.chargecar.org/data/327',
 'http://www.chargecar.org/data/326',
 'http://www.chargecar.org/data/301',
 'http://www.chargecar.org/data/554',
 'http://www.chargecar.org/data/396',
 'http://www.chargecar.org/data/395',
 'http://www.chargecar.org/data/394',
 'http://www.chargecar.org/data/397',
 'http://www.chargecar.org/data/505',
 'http://www.chargecar.org/data/316',
 'http://www.chargecar.org/data/288',
 'http://www.chargecar.org/data/330',
 'http://www.chargecar.org/data/513',
 'http://www.chargecar.org/data/510',
 'http://www.chargecar.org/data/514',
 'http://www.chargecar.org/data/511',
 'http://www.chargecar.org/data/516',
 'http://www.chargecar.org/data/506',
 'http://www.chargecar.org/data/508',
 'http://www.chargecar.org/data/509',
 'http://www.chargecar.org/data/476',
 'http://www.chargecar.org/data/374',
 'http://www.chargecar.org/data/390',
 'http://www.chargecar.org/data/340',
 'http://www.chargecar.org/data/300',
 'http://www.chargecar.org/data/391',
 'http://www.chargecar.org/data/290',
 'http://www.chargecar.org/data/299',
 'http://www.chargecar.org/data/266',
 'http://www.chargecar.org/data/496',
 'http://www.chargecar.org/data/303',
 'http://www.chargecar.org/data/207',
 'http://www.chargecar.org/data/494',
 'http://www.chargecar.org/data/495',
 'http://www.chargecar.org/data/497',
 'http://www.chargecar.org/data/305',
 'http://www.chargecar.org/data/304',
 'http://www.chargecar.org/data/499',
 'http://www.chargecar.org/data/498',
 'http://www.chargecar.org/data/500',
 'http://www.chargecar.org/data/113',
 'http://www.chargecar.org/data/112',
 'http://www.chargecar.org/data/519',
 'http://www.chargecar.org/data/520',
 'http://www.chargecar.org/data/302',
 'http://www.chargecar.org/data/673',
 'http://www.chargecar.org/data/676',
 'http://www.chargecar.org/data/203',
 'http://www.chargecar.org/data/331',
 'http://www.chargecar.org/data/202',
 'http://www.chargecar.org/data/201',
 'http://www.chargecar.org/data/690',
 'http://www.chargecar.org/data/400',
 'http://www.chargecar.org/data/328',
 'http://www.chargecar.org/data/528',
 'http://www.chargecar.org/data/518',
 'http://www.chargecar.org/data/515',
 'http://www.chargecar.org/data/451',
 'http://www.chargecar.org/data/517',
 'http://www.chargecar.org/data/526',
 'http://www.chargecar.org/data/413',
 'http://www.chargecar.org/data/450',
 'http://www.chargecar.org/data/412',
 'http://www.chargecar.org/data/524',
 'http://www.chargecar.org/data/414',
 'http://www.chargecar.org/data/392',
 'http://www.chargecar.org/data/591',
 'http://www.chargecar.org/data/466',
 'http://www.chargecar.org/data/692',
 'http://www.chargecar.org/data/465',
 'http://www.chargecar.org/data/691',
 'http://www.chargecar.org/data/464',
 'http://www.chargecar.org/data/571',
 'http://www.chargecar.org/data/594',
 'http://www.chargecar.org/data/589',
 'http://www.chargecar.org/data/588',
 'http://www.chargecar.org/data/595',
 'http://www.chargecar.org/data/596',
 'http://www.chargecar.org/data/560',
 'http://www.chargecar.org/data/570',
 'http://www.chargecar.org/data/557',
 'http://www.chargecar.org/data/559',
 'http://www.chargecar.org/data/564',
 'http://www.chargecar.org/data/562',
 'http://www.chargecar.org/data/563',
 'http://www.chargecar.org/data/590',
 'http://www.chargecar.org/data/561',
 'http://www.chargecar.org/data/677',
 'http://www.chargecar.org/data/529',
 'http://www.chargecar.org/data/525',
 'http://www.chargecar.org/data/523',
 'http://www.chargecar.org/data/449',
 'http://www.chargecar.org/data/572',
 'http://www.chargecar.org/data/620',
 'http://www.chargecar.org/data/593',
 'http://www.chargecar.org/data/598',
 'http://www.chargecar.org/data/621',
 'http://www.chargecar.org/data/592',
 'http://www.chargecar.org/data/597',
 'http://www.chargecar.org/data/622',
 'http://www.chargecar.org/data/655',
 'http://www.chargecar.org/data/611',
 'http://www.chargecar.org/data/667',
 'http://www.chargecar.org/data/639',
 'http://www.chargecar.org/data/423',
 'http://www.chargecar.org/data/431',
 'http://www.chargecar.org/data/379',
 'http://www.chargecar.org/data/459',
 'http://www.chargecar.org/data/456',
 'http://www.chargecar.org/data/457',
 'http://www.chargecar.org/data/427',
 'http://www.chargecar.org/data/458',
 'http://www.chargecar.org/data/462',
 'http://www.chargecar.org/data/463',
 'http://www.chargecar.org/data/212',
 'http://www.chargecar.org/data/432',
 'http://www.chargecar.org/data/428',
 'http://www.chargecar.org/data/422',
 'http://www.chargecar.org/data/200',
 'http://www.chargecar.org/data/420',
 'http://www.chargecar.org/data/455',
 'http://www.chargecar.org/data/30',
 'http://www.chargecar.org/data/42',
 'http://www.chargecar.org/data/440',
 'http://www.chargecar.org/data/683',
 'http://www.chargecar.org/data/688',
 'http://www.chargecar.org/data/29',
 'http://www.chargecar.org/data/670',
 'http://www.chargecar.org/data/8',
 'http://www.chargecar.org/data/641',
 'http://www.chargecar.org/data/53',
 'http://www.chargecar.org/data/470',
 'http://www.chargecar.org/data/37',
 'http://www.chargecar.org/data/23',
 'http://www.chargecar.org/data/674',
 'http://www.chargecar.org/data/461',
 'http://www.chargecar.org/data/32',
 'http://www.chargecar.org/data/640',
 'http://www.chargecar.org/data/682',
 'http://www.chargecar.org/data/429',
 'http://www.chargecar.org/data/421',
 'http://www.chargecar.org/data/31',
 'http://www.chargecar.org/data/668',
 'http://www.chargecar.org/data/629',
 'http://www.chargecar.org/data/686',
 'http://www.chargecar.org/data/25',
 'http://www.chargecar.org/data/665',
 'http://www.chargecar.org/data/22',
 'http://www.chargecar.org/data/27',
 'http://www.chargecar.org/data/47',
 'http://www.chargecar.org/data/41',
 'http://www.chargecar.org/data/50',
 'http://www.chargecar.org/data/84',
 'http://www.chargecar.org/data/632',
 'http://www.chargecar.org/data/9',
 'http://www.chargecar.org/data/669',
 'http://www.chargecar.org/data/128',
 'http://www.chargecar.org/data/672',
 'http://www.chargecar.org/data/35',
 'http://www.chargecar.org/data/21',
 'http://www.chargecar.org/data/664',
 'http://www.chargecar.org/data/681',
 'http://www.chargecar.org/data/44',
 'http://www.chargecar.org/data/33',
 'http://www.chargecar.org/data/687',
 'http://www.chargecar.org/data/619',
 'http://www.chargecar.org/data/85',
 'http://www.chargecar.org/data/442',
 'http://www.chargecar.org/data/522',
 'http://www.chargecar.org/data/671',
 'http://www.chargecar.org/data/26',
 'http://www.chargecar.org/data/689',
 'http://www.chargecar.org/data/633',
 'http://www.chargecar.org/data/17',
 'http://www.chargecar.org/data/426',
 'http://www.chargecar.org/data/54',
 'http://www.chargecar.org/data/684',
 'http://www.chargecar.org/data/435',
 'http://www.chargecar.org/data/20',
 'http://www.chargecar.org/data/19',
 'http://www.chargecar.org/data/685',
 'http://www.chargecar.org/data/448',
 'http://www.chargecar.org/data/521',
 'http://www.chargecar.org/data/425',
 'http://www.chargecar.org/data/24',
 'http://www.chargecar.org/data/424',
 'http://www.chargecar.org/data/40',
 'http://www.chargecar.org/data/675',
 'http://www.chargecar.org/data/468',
 'http://www.chargecar.org/data/430',
 'http://www.chargecar.org/data/634',
 'http://www.chargecar.org/data/469',
 'http://www.chargecar.org/data/18',
 'http://www.chargecar.org/data/49',
 'http://www.chargecar.org/data/436',
 'http://www.chargecar.org/data/460',
 'http://www.chargecar.org/data/527',
 'http://www.chargecar.org/data/250',
 'http://www.chargecar.org/data/652',
 'http://www.chargecar.org/data/662',
 'http://www.chargecar.org/data/433',
 'http://www.chargecar.org/data/434',
 'http://www.chargecar.org/data/445',
 'http://www.chargecar.org/data/444',
 'http://www.chargecar.org/data/446',
 'http://www.chargecar.org/data/443',
 'http://www.chargecar.org/data/447',
 'http://www.chargecar.org/data/586',
 'http://www.chargecar.org/data/452',
 'http://www.chargecar.org/data/454',
 'http://www.chargecar.org/data/93',
 'http://www.chargecar.org/data/92',
 'http://www.chargecar.org/data/654',
 'http://www.chargecar.org/data/534',
 'http://www.chargecar.org/data/643',
 'http://www.chargecar.org/data/659',
 'http://www.chargecar.org/data/657',
 'http://www.chargecar.org/data/656',
 'http://www.chargecar.org/data/647',
 'http://www.chargecar.org/data/645',
 'http://www.chargecar.org/data/644',
 'http://www.chargecar.org/data/650',
 'http://www.chargecar.org/data/653',
 'http://www.chargecar.org/data/658',
 'http://www.chargecar.org/data/660',
 'http://www.chargecar.org/data/649',
 'http://www.chargecar.org/data/248',
 'http://www.chargecar.org/data/651',
 'http://www.chargecar.org/data/333',
 'http://www.chargecar.org/data/342',
 'http://www.chargecar.org/data/373',
 'http://www.chargecar.org/data/253',
 'http://www.chargecar.org/data/291',
 'http://www.chargecar.org/data/484',
 'http://www.chargecar.org/data/490',
 'http://www.chargecar.org/data/486',
 'http://www.chargecar.org/data/477',
 'http://www.chargecar.org/data/487',
 'http://www.chargecar.org/data/617',
 'http://www.chargecar.org/data/539',
 'http://www.chargecar.org/data/537',
 'http://www.chargecar.org/data/536',
 'http://www.chargecar.org/data/538',
 'http://www.chargecar.org/data/540',
 'http://www.chargecar.org/data/535',
 'http://www.chargecar.org/data/616',
 'http://www.chargecar.org/data/618',
 'http://www.chargecar.org/data/615',
 'http://www.chargecar.org/data/614',
 'http://www.chargecar.org/data/382',
 'http://www.chargecar.org/data/380',
 'http://www.chargecar.org/data/553',
 'http://www.chargecar.org/data/551',
 'http://www.chargecar.org/data/383',
 'http://www.chargecar.org/data/381',
 'http://www.chargecar.org/data/357',
 'http://www.chargecar.org/data/356',
 'http://www.chargecar.org/data/471',
 'http://www.chargecar.org/data/475',
 'http://www.chargecar.org/data/362',
 'http://www.chargecar.org/data/415',
 'http://www.chargecar.org/data/473',
 'http://www.chargecar.org/data/418',
 'http://www.chargecar.org/data/552',
 'http://www.chargecar.org/data/550',
 'http://www.chargecar.org/data/361',
 'http://www.chargecar.org/data/359',
 'http://www.chargecar.org/data/416',
 'http://www.chargecar.org/data/378',
 'http://www.chargecar.org/data/360',
 'http://www.chargecar.org/data/196',
 'http://www.chargecar.org/data/195',
 'http://www.chargecar.org/data/193',
 'http://www.chargecar.org/data/194',
 'http://www.chargecar.org/data/2',
 'http://www.chargecar.org/data/4',
 'http://www.chargecar.org/data/6',
 'http://www.chargecar.org/data/437',
 'http://www.chargecar.org/data/13',
 'http://www.chargecar.org/data/3',
 'http://www.chargecar.org/data/1',
 'http://www.chargecar.org/data/5',
 'http://www.chargecar.org/data/7']
    

    """
      Try to find float first and then int.
      But always return the first number found
    """
    def get_num(self, x):
        
        l = re.findall("\d+.\d+", x)
        if(len(l)>0):
            return l[0]
        else:
            l = re.findall("\d+", x)
            if(len(l)>0):
                return l[0]
            else:
                return "missing"
    
    def parse(self, response):
       
        sel = Selector(response)
        sites = sel.xpath('//div[@id="extra_meta_data"]/p')
        items = []

        for site in sites:
            item = Website()

            ### ITEM -- description ###
            list_describe = site.xpath('text()').extract()
            #list_describe seemed has already been splitted...
            str_describe = ""
            for i in list_describe:
                str_describe = str_describe + i
            item['description'] = self.get_num(str_describe)
            #item['description'] = list_describe[1]
            
            ### ITEM -- feature ###
            item['feature'] = site.xpath('b/text()').extract()
            
            ### ITEM -- TripID
            cur_url = response.url
            cur_url_list = cur_url.split('/')
            item['tripID'] = cur_url_list[-1]

            items.append(item)

        return items
        
